import React, { Fragment, useState } from "react";
import { Meta, StoryObj } from "@storybook/react";
import EnTable from "./enTable";

const meta: Meta<typeof EnTable> = {
  component: EnTable,
  title: "tm/EnTable",
  argTypes: {
  },
};

export default meta;

type Story = StoryObj<typeof EnTable>;

export const Primary: Story = (args) => {


  return (
    <Fragment>
        <EnTable {...args} />
    </Fragment>
  )

}

Primary.args = {
    totalPageSize: 12,
    rows: [{
        id: '#172589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172581',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172582',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172583',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172584',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172585',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172586',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172587',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172588',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#173589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#132589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#112589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242580',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242581',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242582',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242583',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242584',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242585',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242586',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242587',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242588',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1212589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124012589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124250289',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124203589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124204589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124205589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124205589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124258903',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242452589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172581',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172582',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172583',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172584',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172585',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172586',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172587',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#172588',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#173589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#132589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#112589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242580',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242581',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242582',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242583',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242584',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242585',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242586',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242587',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242588',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1212589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124012589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124250289',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124203589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124204589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124205589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124205589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#124258903',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      },{
        id: '#1242452589',
        customerName: 'Yatra',
        projectName: 'London Vlogs',
        orderType: 'Multiple  , Mixed',
        dueDate: "March 10, 2022",
        orderDate: "March 10, 2022",
        status: "Active",
      }]  
    
};



